name: Despliega

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the React App
        run: npm run build  

      - name: Build React App with Docker
        run: |
          docker build -t react-build .
          CONTAINER_ID=$(docker create react-build)
          docker cp $CONTAINER_ID:/app/build ./build
          docker rm $CONTAINER_ID

      - name: Save build folder (para Docker local)
        run: |
          rm -rf nginx-deploy
          mkdir nginx-deploy
          cp -r build/* nginx-deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build




